[workspace]
resolver = "2"
members = ["crates/ast", "crates/db", "crates/diagnostics","crates/driver", "crates/elaborator", "crates/lotus", "crates/lsp", "crates/structure", "crates/syntax", "xtask"]
default-members = ["crates/lotus"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/SrGaabriel/leander"
authors = ["Gabriel"]

[workspace.dependencies]
# Internal

ast = { path = "crates/ast" }
db = { path = "crates/db" }
driver = { path = "crates/driver" }
syntax = { path = "crates/syntax" }
diagnostics = { path = "crates/diagnostics" }
structure = { path = "crates/structure" }
elaborator = { path = "crates/elaborator" }

# External
clap = { version = "^4.6", features = ["derive"] }

cstree = { version = "^0.14", features = ["derive", "serialize", "lasso", "multi_threaded_interning"] }
salsa = { version = "^0.26" }
ungrammar = "^1.16"
ariadne = { version = "^0.7", features = ["auto-color"], git = "https://codeberg.org/zesterer/ariadne" }
text-size = "^1.1"

anyhow = "1"
thiserror = "1"

prettyplease = "^0.2"
syn = "2"
quote = "1"
proc-macro2 = "1"
strum = { version = "^0.28", features = ["derive"] }

heck = "^0.5"
rustc-hash = "^2.1"
la-arena = "^0.3"

tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "^1", features = ["full"] }
tower-lsp = "^0.20"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
return_self_not_must_use = "allow"
cast_possible_truncation = "allow"
disallowed_methods = "deny"
