[workspace]
default-members = ["crates/lotus"]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.package]
authors = ["Gabriel"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/SrGaabriel/leander"
version = "0.1.0"

[workspace.dependencies]
# Internal
ast = { path = "crates/ast" }
db = { path = "crates/db" }
diagnostics = { path = "crates/diagnostics" }
driver = { path = "crates/driver" }
elaborator = { path = "crates/elaborator" }
literals = { path = "crates/literals" }
nir = { path = "crates/nir" }
structure = { path = "crates/structure" }
syntax = { path = "crates/syntax" }

# External
anyhow = "1"
ariadne = { version = "^0.7", features = [
    "auto-color",
], git = "https://codeberg.org/zesterer/ariadne" }
clap = { version = "^4.6", features = ["derive"] }
cstree = { version = "^0.14", features = [
    "derive",
    "lasso",
    "multi_threaded_interning",
    "serialize",
] }
heck = "^0.5"
la-arena = "^0.3"
num-bigint = "^0.4"
num-rational = "^0.4"
prettyplease = "^0.2"
proc-macro2 = "1"
quote = "1"
rustc-hash = "^2.1"
salsa = { version = "^0.26" }
strum = { version = "^0.28", features = ["derive"] }
syn = "2"
text-size = "^1.1"
thiserror = "2"
tokio = { version = "^1", features = ["full"] }
tower-lsp = "^0.20"
tracing = "0.1"
tracing-subscriber = "0.3"
ungrammar = "^1.16"

[workspace.lints.clippy]
cast_possible_truncation = "allow"
disallowed_methods = "deny"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
pedantic = { level = "warn", priority = -1 }
return_self_not_must_use = "allow"
