[package]
name = "ast"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cstree.workspace = true
db.workspace = true
diagnostics.workspace = true
salsa.workspace = true
syntax.workspace = true
ungrammar.workspace = true

[lints]
workspace = true
