[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "nir"
repository.workspace = true
version.workspace = true

[dependencies]
db.workspace = true
elaborator.workspace = true
literals.workspace = true
salsa.workspace = true
text-size.workspace = true
tracing.workspace = true

[lints]
workspace = true
