[package]
name = "elaborator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ast.workspace = true
db.workspace = true
diagnostics.workspace = true
salsa.workspace = true
structure.workspace = true

[lints]
workspace = true
