[package]
name = "lotus"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
diagnostics.workspace = true
driver.workspace = true
elaborator.workspace = true
nir.workspace = true
structure.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
